services:
  users:
    build: ./users
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      JWT_SECRET: supersecret

  products:
    build: ./products
    ports:
      - "5002:5002"
    environment:
      PORT: 5002
      JWT_SECRET: supersecret

  orders:
    build: ./orders
    ports:
      - "5003:5003"
    environment:
      PORT: 5003
      JWT_SECRET: supersecret

  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      JWT_SECRET: supersecret
      USERS_SERVICE_URL: http://users:5001
      PRODUCTS_SERVICE_URL: http://products:5002
      ORDERS_SERVICE_URL: http://orders:5003
    depends_on:
      - users
      - products
      - orders
